"""
ARKAINBRAIN — Godot 4 Export Package Generator (Phase 10)

Generates a Godot 4 project scaffold with:
- project.godot configuration
- .tscn scene files with reel/symbol node hierarchy
- .gd scripts for spin logic, symbol rendering, win evaluation
- .tres resource files for symbol/reel data
- Export presets for Web, Android, iOS
"""

import json
import zipfile
from datetime import datetime
from pathlib import Path


PROJECT_GODOT = '''[gd_resource type="ProjectSettings" load_steps=1 format=3]

; Auto-generated by ARKAINBRAIN Phase 10 Export
; Game: {title}

[application]
config/name="{title}"
run/main_scene="res://scenes/Main.tscn"
config/features=PackedStringArray("4.2")

[display]
window/size/viewport_width=1920
window/size/viewport_height=1080
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[rendering]
renderer/rendering_method="mobile"
'''

MAIN_SCENE = '''[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="res://scripts/SlotMachine.gd" id="1"]
[ext_resource type="Script" path="res://scripts/UIController.gd" id="2"]

[node name="Main" type="Node2D"]

[node name="SlotMachine" type="Node2D" parent="."]
script = ExtResource("1")
grid_cols = {cols}
grid_rows = {rows}

[node name="ReelContainer" type="Node2D" parent="SlotMachine"]
position = Vector2(460, 200)

{reel_nodes}

[node name="UI" type="CanvasLayer" parent="."]

[node name="UIController" type="Control" parent="UI"]
anchors_preset = 15
script = ExtResource("2")

[node name="SpinButton" type="Button" parent="UI/UIController"]
offset_left = 800
offset_top = 700
offset_right = 1120
offset_bottom = 780
text = "SPIN"

[node name="BalanceLabel" type="Label" parent="UI/UIController"]
offset_left = 50
offset_top = 30
offset_right = 300
offset_bottom = 60
text = "Balance: $1,000.00"

[node name="WinLabel" type="Label" parent="UI/UIController"]
offset_left = 700
offset_top = 600
offset_right = 1220
offset_bottom = 660
horizontal_alignment = 1
text = ""
'''

SLOT_MACHINE_GD = '''# Auto-generated by ARKAINBRAIN Phase 10 Export
# Game: {title}
extends Node2D

## Grid configuration
@export var grid_cols: int = {cols}
@export var grid_rows: int = {rows}
@export var ways_or_lines: int = {ways}

## Spin settings
@export var spin_duration: float = 1.5
@export var reel_stop_delay: float = 0.2
@export var reel_speed: float = 2000.0

## Data
var config: Dictionary
var paytable: Array
var reel_strips: Array
var features: Array

var is_spinning: bool = false
var current_result: Array = []

signal spin_started
signal spin_complete(result: Array)
signal win_evaluated(total_win: float, win_lines: Array)

func _ready():
    _load_game_data()
    print("[SlotMachine] Loaded: %d symbols, %d reels" % [paytable.size(), reel_strips.size()])

func _load_game_data():
    config = _load_json("res://data/config.json")
    paytable = _load_json("res://data/paytable.json")
    reel_strips = _load_json("res://data/reelstrips.json")
    features = _load_json("res://data/features.json")

func _load_json(path: String) -> Variant:
    if not FileAccess.file_exists(path):
        push_warning("Missing data file: " + path)
        return {{}}
    var file = FileAccess.open(path, FileAccess.READ)
    var text = file.get_as_text()
    return JSON.parse_string(text)

func spin():
    if is_spinning:
        return
    is_spinning = true
    emit_signal("spin_started")

    # NOTE: In production, request result from game server
    # This is a client-side scaffold for visual testing only
    current_result = _generate_local_result()

    await _animate_reels()
    emit_signal("spin_complete", current_result)
    _evaluate_wins()
    is_spinning = false

func _generate_local_result() -> Array:
    """Generate a random result for testing. Replace with server response."""
    var result = []
    for col in range(grid_cols):
        var reel = []
        var strip = reel_strips[col] if col < reel_strips.size() else []
        for row in range(grid_rows):
            if strip.size() > 0:
                reel.append(strip[randi() % strip.size()])
            else:
                reel.append("H1")
        result.append(reel)
    return result

func _animate_reels():
    """Animate reel spinning. Override for custom animations."""
    for col in range(grid_cols):
        # Start reel spin animation
        var reel_node = get_node_or_null("ReelContainer/Reel%d" % col)
        if reel_node:
            var tween = create_tween()
            tween.tween_property(reel_node, "position:y", -500.0, 0.1)
            tween.tween_property(reel_node, "position:y", 0.0, spin_duration)

        await get_tree().create_timer(reel_stop_delay).timeout

func _evaluate_wins():
    """Evaluate wins from current result. Scaffold for server-verified results."""
    var total_win = 0.0
    var win_lines = []
    # TODO: Implement ways/lines evaluation using paytable data
    # In production, wins come from the game server
    emit_signal("win_evaluated", total_win, win_lines)
'''

UI_CONTROLLER_GD = '''# Auto-generated by ARKAINBRAIN Phase 10 Export
extends Control

@onready var slot_machine = get_node("/root/Main/SlotMachine")
@onready var spin_button = $SpinButton
@onready var balance_label = $BalanceLabel
@onready var win_label = $WinLabel

var balance: float = 1000.0
var bet_amount: float = 1.0

func _ready():
    spin_button.pressed.connect(_on_spin_pressed)
    slot_machine.spin_started.connect(_on_spin_started)
    slot_machine.spin_complete.connect(_on_spin_complete)
    slot_machine.win_evaluated.connect(_on_win_evaluated)
    _update_ui()

func _on_spin_pressed():
    if balance < bet_amount:
        return
    balance -= bet_amount
    _update_ui()
    slot_machine.spin()

func _on_spin_started():
    spin_button.disabled = true
    win_label.text = ""

func _on_spin_complete(_result):
    spin_button.disabled = false

func _on_win_evaluated(total_win: float, _win_lines: Array):
    if total_win > 0:
        balance += total_win
        win_label.text = "WIN: $%.2f" % total_win
    _update_ui()

func _update_ui():
    balance_label.text = "Balance: $%.2f" % balance
'''

EXPORT_PRESETS = '''[preset.0]
name="Web"
platform="Web"
runnable=true
export_filter="all_resources"

[preset.0.options]
html/export_icon=true
html/canvas_resize_policy=2

[preset.1]
name="Android"
platform="Android"
runnable=true
export_filter="all_resources"

[preset.2]
name="iOS"
platform="iOS"
runnable=true
export_filter="all_resources"
'''


def generate_godot_package(output_dir: str, game_title: str, config: dict,
                           symbols: list, reels: list, features: list,
                           sim_data: dict = None, **kwargs) -> str:
    """Generate Godot 4 project scaffold."""
    od = Path(output_dir)
    export_dir = od / "09_export"
    export_dir.mkdir(parents=True, exist_ok=True)

    slug = game_title.lower().replace(" ", "_").replace("'", "")[:30]
    zip_path = export_dir / f"{slug}_godot4.zip"

    cols = config.get("grid_cols", 5)
    rows = config.get("grid_rows", 3)
    ways = config.get("ways_or_lines", 243)

    # Build reel nodes for scene
    reel_nodes = ""
    for i in range(cols):
        reel_nodes += f'''[node name="Reel{i}" type="Node2D" parent="SlotMachine/ReelContainer"]
position = Vector2({i * 200}, 0)

'''

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        pfx = slug

        # project.godot
        zf.writestr(f"{pfx}/project.godot", PROJECT_GODOT.format(title=game_title))

        # Export presets
        zf.writestr(f"{pfx}/export_presets.cfg", EXPORT_PRESETS)

        # Scenes
        zf.writestr(f"{pfx}/scenes/Main.tscn",
                     MAIN_SCENE.format(cols=cols, rows=rows, reel_nodes=reel_nodes))

        # Scripts
        zf.writestr(f"{pfx}/scripts/SlotMachine.gd",
                     SLOT_MACHINE_GD.format(title=game_title, cols=cols, rows=rows, ways=ways))
        zf.writestr(f"{pfx}/scripts/UIController.gd", UI_CONTROLLER_GD)

        # Data files
        zf.writestr(f"{pfx}/data/config.json", json.dumps(config, indent=2))
        zf.writestr(f"{pfx}/data/paytable.json", json.dumps(symbols, indent=2))
        zf.writestr(f"{pfx}/data/reelstrips.json", json.dumps(reels, indent=2))
        zf.writestr(f"{pfx}/data/features.json", json.dumps(features, indent=2))

        if sim_data:
            zf.writestr(f"{pfx}/data/simulation.json", json.dumps(sim_data, indent=2))

        # Symbol .tres resources
        for sym in symbols:
            name = sym.get("name", "Unknown")
            slug_s = name.lower().replace(" ", "_")
            pays = sym.get("payouts", [])
            pays_str = ", ".join(str(p) for p in pays) if pays else "0"
            tres = f'''[gd_resource type="Resource" format=3]
[resource]
script = null
symbol_name = "{name}"
payouts = [{pays_str}]
sprite_path = "res://sprites/symbols/{slug_s}.png"
'''
            zf.writestr(f"{pfx}/resources/symbols/{slug_s}.tres", tres)

        # Sprite placeholders
        for sym in symbols:
            slug_s = sym.get("name", "sym").lower().replace(" ", "_")
            zf.writestr(f"{pfx}/sprites/symbols/{slug_s}/.gitkeep", "")

        # Copy art if available
        art_dir = od / "04_art"
        if art_dir.exists():
            for img in art_dir.rglob("*"):
                if img.is_file() and img.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp"):
                    zf.write(img, f"{pfx}/sprites/{img.relative_to(art_dir)}")

        # README
        zf.writestr(f"{pfx}/README.md", f"""# {game_title} — Godot 4 Project
Generated by ARKAINBRAIN Phase 10 on {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Quick Start
1. Open this folder as a Godot 4.2+ project
2. Main scene: `scenes/Main.tscn`
3. Game data in `data/*.json`
4. Add symbol sprites to `sprites/symbols/`

## Configuration
- Grid: {cols}×{rows}, Ways/Lines: {ways}
- RTP: {config.get('target_rtp')}%, Max Win: {config.get('max_win_multiplier')}x
- Symbols: {len(symbols)}, Features: {len(features)}

## Export Presets
Pre-configured for Web, Android, and iOS.

## Important
Client-side scaffold only. Connect to a certified RNG game server for production.
""")

    return str(zip_path)
